services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: sh -c "npm install && npm run dev"
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - /app/node_modules
    networks:
      - pokytalk-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: sh -c "npm install && npm run dev"
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://248c5199d0ec.ngrok-free.app
    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - pokytalk-network

networks:
  pokytalk-network:
    driver: bridge
